apiVersion: v1
data:
  .dockerconfigjson: ENC[AES256_GCM,data:WQXv22ym23gCUfDodvOConcVI7N5dRIm9omq2kR7UNI+eUEQaBhgbri2uRrlm9nuZQlvByPi6AVPKzUPaOQE/9BgTlwBzq150x2s/wDIRdL/8MzojzJeU6P1oju3OSbNGOTzTEJF6OjzZLb0dxA9D+MPQnrAjD+PlBpRsHwTBs+iWxGJn4bosjV1DFHylwE7tqerf8DPrlXtOBmEhbBBws5PePbg9Nne/j6MK+MfDxexHCE5XjBPZGNb6Cf/paKC5WfQiWnt+XRMCJnkFScycoyZQFQbAaV5Qd/7cOroTQEefVStymge8b0p8o6NytKPgXAKIR4UB00=,iv:DTJvvy6VombNLu1WldJ4vTUcuEY340kSMgr4cqeiuhM=,tag:a7t6PXOdIZXxYoAnG1MCgA==,type:str]
kind: Secret
metadata:
  name: github-docker
  namespace: flux-system
type: kubernetes.io/dockerconfigjson
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1qvesyd4zyqs5p40n8gr2ngjvsg6surf9e37h3xv7rm7m5lsgz5jsetg3ql
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJN3NBZVFrUFpqWVJlS2ZM
        SzJ6RVp1WGVrKzlTNFY3dDRqZjlXdUFHS1JrCkplN1Z3YmRqSm9ORlFFeENaMWh3
        bTVFYXNEeG9PeHZ5VXd1V3VyY1c1RHcKLS0tIHNISW1iRDFlOUN3Sk9kYlZPcjF5
        SS9nNU8xVTdiRHRWWkVUR0xabzVxYTQKNO8dttnyQbsA8nYMXGAeYjtWILqhaRTz
        8DU//gwDgtOmTOuQJtC3jA2fYAE/oj5mhMGuUSBMPfGbnkumqB+YMQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-07-20T08:05:44Z"
  mac: ENC[AES256_GCM,data:FneM0yVTbuanNdbd8BuPw148jEsdKW95gtiUNfctchAy0OE4lpJiS3FTUVslXlkZmbDbEySIPijJNumgLo4G+7yAm9lGZCvUSvNBPST53J10oitf7yEzPezynyZGL0VYrSuAmexEcevq10zyqFgKdXT+4bCOsSi3rWHDozWCXeM=,iv:TPqyRgOSwkyuun2YaYGi4NDdppYeUH1ZxQcaTGZBtcw=,tag:ZTVjURuPux/fPSWjzxIibw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
