apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/fastapi-example
  - git-secret.enc.yaml
patches:
  - path: controller.yaml
    target:
      kind: Kustomization
  - path: imageupdateautomation.yaml
    target:
      kind: ImageUpdateAutomation
