adminUser:
  passwordHash: ENC[AES256_GCM,data:9perX/E92La7I+CO9jirh0n9aB0kl5I7H9Wmtk6aGrWq9TQ4Lya6rJ5FtVfEWZWyna0ch8tv0/hSTW6t,iv:gC4h33cOrcmA3O3rDLySWXBkucqxivH5thwPuk77S6s=,tag:Smop2c2EYf8rIYSJ7MgmWw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1qvesyd4zyqs5p40n8gr2ngjvsg6surf9e37h3xv7rm7m5lsgz5jsetg3ql
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlR0RjdHJYMkhVbnpnZ0Fv
        Mms2dGVoVnpmaU5Rd000MjFtOWttODRjY1FvCnVicXQ3cnRGSVhtbjZEOUtRemRm
        Qm4wRHNCZjc2MFppK1VZbi9iWTk2MkkKLS0tIDM2QnY0cmhOSjJNV3ZFQlNGaXdt
        MmxyRlh6V1RnaU1sUkxqYktxQWh3QUUK3xOFl5ZI2xOJJJpgxEhKl3SpNaqtLT3H
        9GqOAy4CErF6HkY5LrzetEPAeYykro6XejTYqlQxw88XslGXd4HpDg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-07-18T16:56:11Z"
  mac: ENC[AES256_GCM,data:QEVeCGPpEq1pA41wxVh9uKT88DH7Pqt0Y/bLM5wr0eEcNF/tCin5v+HMOdBmvnBChXczTEnohFXV2Kl4SOAcvTvAqRulWqHtYE680TFOqsdsKw66cfwnEyb2U7wPvD50vNL2sB+OTBJZvoyFQS3RBELCmSMbMiJ9iWwGa9w6oSs=,iv:TnjkiOtJNOPTm892zX9zr5zrr7viBRqIAOwqZF8ZlRM=,tag:rmjsjSUK8rnP2ZFGLdxuZg==,type:str]
  pgp: []
  unencrypted_suffix: _unencrypted
  version: 3.7.3
